sudo: required
language: node_js
services: mongodb
node_js:
- '8'
env:
- NODE_ENV=development TEST_DB_URI="mongodb://test:test@127.0.0.1/test_db"
matrix:
  include:
  - node_js: '10'
  allow_failures:
  - node_js: '10'
notifications:
  disabled: true
before_install:
- npm install -g codecov
install:
- npm install
before_script:
- sleep 10
- mongo test_db --eval 'db.createUser({user:"test",pwd:"test",roles:["readWrite"]});'
script:
- node index.js &
- npm run check-coverage
- codecov
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: heroku
  api_key:
    secure: gfJQ4NRFfxti43ao2as0lhb99axRTMCYBB1U6ge8WyZIfn15DsLPGyrVNnPv9UnjxDGE0Z5x0mMbdvOoAf9wtiU3mYex4dh/Xkv1OnlrQnT2CQ7gYxJI69raWH2ttCVrYMk1jzuEcxtI13QspWVh+hgFr9efyDESNw6AUnd+rwBKrZX40WleroAhpYv/O2AxYjhyN9ZK/8G+kKGRai6GmfA9v7DMYRKAI7JmnQkAVEAcsS8VvqGn/9+ivz0o9dOb3wFOmfU25p4M0+KEHORi2P7YrOhzI69VeuwbwRK1MvGtxjR/g5ilh2qWMKjCTvxIQgASzVsvRgh1USCzDl49edOomd8w9xVAB3HMBE94XvSrOaKylydFzeFl0EHY5BmP1kePHkWojdsns1k3K0FYxsQhyblpdW7zCIMPwf4gNsVbu+HKq8Re2VsnmYT1LKJsZJQK8d3HMq4JiXShMMhgH5HKtZnRRokVrSmiLsW4AHnnJwEbJUWpALRp0+82mNkYjXVJa6oRaBSxpZH2mJTlUrjsc2sZornPKMz95OKN2qjPbQ832pBJOPb/mL9dAs61u4vWFV+HdukIN2ynfEBQc09aQzJfphty/cK2H1pSoTSc1Ly/4pc9jU/04HUbbVSwhx9ZIPLO5oTqACb7bF3h4BbBtm12afjHNoSFyVNzttY=
  app: rs-uno-server-v1
  on:
    repo: udyat-miet/uno_server_v1
