version: '3'
services:
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=uno_db_admin
      - MONGO_INITDB_ROOT_PASSWORD=uno_db_password
    image: mongo
    volumes:
      - /data/db
    ports:
      - '27017:27017'
  app:
    image: uno_server_v1:latest
    container_name: uno_server_v1
    environment:
      - NODE_ENV=development
      - TEST_DB_URI=mongodb://uno_db_admin:uno_db_password@mongo/
    volumes:
      - /uno/node_modules
      - ./src:/uno/src
    links:
      - mongo
    build:
      context: .
    ports:
      - '3000:8080'
    command: sh -c 'npm install && npm run dev'
